# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  release: 
    types: [ published ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner Fthat the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: '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'

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: abatilo/actions-poetry@v2.1.2
        with:
          poetry-version: "1.1.6"

      - name: Build distribution
        run: poetry build

      - name: Deploy to Azure
        run: |
          pip install twine keyring artifacts-keyring
          twine upload --repository-url ${{ secrets.AZURE_ARTIFACTS_FEED }} -u 'az' -p ${{ secrets.AZURE_ARTIFACTS_FEED_TOKEN }} dist/* --skip-existing
